options:
  cd-printer-hide-class: false
  cd-printer-simple-output: false
  cd-printer-show-config: true
  cd-printer-hide-namespace: false
  cd-printer-anybar: true
  cd-printer-anybar-port: 1738
  cd-printer-dont-format-classname: false
markers:
  cd-pass: "âš¡ pass "
  cd-fail: "ğŸ’€ fail "
  cd-error: "ğŸ˜­ error "
  cd-skipped: "ğŸµ skipped "
  cd-incomplete: "ğŸ¤ª  incomplete"
  cd-risky: "ğŸ”¥ risky"